# Generated by Django 2.2.5 on 2019-09-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=750)),
            ],
        ),
        migrations.CreateModel(
            name='Spaceport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(blank=True)),
                ('details', models.CharField(default='', max_length=200)),
                ('payload', models.CharField(default='', max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launches.Company')),
            ],
        ),
    ]
