# Generated by Django 2.2.5 on 2019-09-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
