# Generated by Django 2.2.5 on 2019-09-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0002_launch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='image',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='launch',
            name='details',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
